name: Lint Resume

on:
  push:
    branches: [main]
    paths:
      - "resumes/docs/**"
      - "resumes/.textlintrc"
  pull_request:
    paths:
      - "resumes/docs/**"
      - "resumes/.textlintrc"

jobs:
  textlint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: resumes
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7
        with:
          node-version-file: resumes/package.json
      - run: npm ci
      - run: npm run lint
